import {
  appSalon01,
  appSalon02,
  bienesRaices01,
  bienesRaices02,
  blackJack01,
  blackJack02,
  blogCoffe01,
  blogCoffe02,
  devfolioArg01,
  devfolioArg02,
  devwebCamp01,
  devwebCamp02,
  devwebCamp03,
  festivalMusica01,
  festivalMusica02,
  festivalMusica03,
  freelancer01,
  freelancer02,
  gifExpertApp01,
  gifExpertApp02,
  hanging01,
  hanging02,
  journalApp01,
  journalApp02,
  maquetaBienesRaices01,
  maquetaBienesRaices02,
  starWars01,
  starWars02,
  store01,
  store02,
  todo01,
  todo02,
  uptask01,
  uptask02,
} from "./index";

export const projectsEs = [
  {
    id: 1,
    image: [bienesRaices01, bienesRaices02],
    title: "Bienes Raíces Sitio Web para Inmobiliaria",
    description: "",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/Bienes_Raices-MVC",
    demo: "https://github.com/Lean-98/Bienes_Raices-MVC",
  },
  {
    id: 2,
    image: [devwebCamp01, devwebCamp02, devwebCamp03],
    title: "DevWebCamp Sitio Web de Conferencias",
    description: "Sitio de Conferencias con Pagos en PayPal, Administración y gestión de usuarios.",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/DevWebCamp-MVC",
    demo: "https://github.com/Lean-98/DevWebCamp-MVC",
  },
  {
    id: 3,
    image: [appSalon01, appSalon02],
    title: "Sitio Web para Barber Shop y Salón de Belleza",
    description: "Proyecto completo de Administración de Citas para Salón de Belleza.",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/App-Salon-mvc",
    demo: "https://github.com/Lean-98/App-Salon-mvc",
  },
  {
    id: 4,
    image: [uptask01, uptask02],
    title: "UpTask Sitio Web Administrador de Proyectos y tareas",
    description: "",
    techstack: ["#POO" ,"#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/UpTask_MVC",
    demo: "https://github.com/Lean-98/UpTask_MVC",
  },
  {
    id: 5,
    image: [journalApp01, journalApp02],
    title: "Sitio Web JournalApp",
    description: "",
    techstack: ["#Material MUI" ,"#JavaScript", "#React", "#Redux", "#Redux Toolkit", "#React Router 6", "#Firebase", "#Cloudinary", "#Jest", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/JournalApp",
    demo: "https://journal-app-2k23.netlify.app",
  },
  {
    id: 6,
    image: [starWars01, starWars02],
    title: "Sitio Web Star Wars",
    description: "",
    techstack: ["#Bootstrap 5" ,"#JavaScript ", "#React", "#SPA", "#React-Router 6.4", "#Jest", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/StarWars-App",
    demo: "https://starwars-spa-app.netlify.app",
  },
  {
    id: 7,
    image: [festivalMusica01, festivalMusica02, festivalMusica03],
    title: "Sitio Web Festival de Música",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#Gulp", "#JavaScript"],
    github: "https://github.com/Lean-98/festival-musica",
    demo: "https://festivalmusica-by-lean98.netlify.app/",
  },
  {
    id: 8,
    image: [todo01, todo02],
    title: "TodoApp gestor de tareas",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#JavaScript", "#Vanilla", "#Vite"],
    github: "https://github.com/Lean-98/TodoApp-V2.0",
    demo: "https://todo-app-by-lean98.netlify.app",
  },
  {
    id: 9,
    image: [devfolioArg01, devfolioArg02],
    title: "Proyecto final para el curso Front-end brindado por Argentina Programa 4.0",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#JavaScript", "#Webpack", "#NPM"],
    github: "https://github.com/Lean-98/PortfolioCv-ARG-4.0",
    demo: "https://lean-98.github.io/PortfolioCv-ARG-4.0",
  },
  {
    id: 10,
    image: [blackJack01, blackJack02],
    title: "BlackJackv2",
    description: "",
    techstack: ["#HTML5" ,"#Bootstrap 5", "#JavaScript", "#Vanilla", "#Vite"],
    github: "https://github.com/Lean-98/BlackJackv2",
    demo: "https://lean-98.github.io/BlackJackv2",
  },
  {
    id: 11,
    image: [hanging01, hanging02],
    title: "Hanging game",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#React", "#Typescript", "#Vite"],
    github: "https://github.com/Lean-98/Hanging_app",
    demo: "https://lean98-hanging.netlify.app",
  },
  {
    id: 12,
    image: [gifExpertApp01, gifExpertApp02],
    title: "GifExpertApp",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#React", "#JavaScript", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/GifExpertApp",
    demo: "https://gif-expertapp-v1.netlify.app",
  },
  {
    id: 13,
    image: [blogCoffe01, blogCoffe02],
    title: "BlogDeCafé",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/blog-coffee",
    demo: "https://blog-coffee-by-lean98.netlify.app",
  },
  {
    id: 14,
    image: [store01, store02],
    title: "Frontend Store",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/front-end-store",
    demo: "https://proyectosweb002.netlify.app",
  },
  {
    id: 15,
    image: [freelancer01, freelancer02],
    title: "Maquetado Sitio Web FreeLancer",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/FreeLancer2k23",
    demo: "https://freelancer-project-001.netlify.app",
  },
  {
    id: 16,
    image: [maquetaBienesRaices01, maquetaBienesRaices02],
    title: "Maquetado del sitio Web Proyecto Bienes Raíces",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#JavaScript"],
    github: "https://github.com/Lean-98/bienes_raices_html-css3",
    demo: "https://bienesraices-by-real10.netlify.app",
  },
];

export const projectsEn = [
  {
    id: 1,
    image: [bienesRaices01, bienesRaices02],
    title: "Real Estate Web Site",
    description: "",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/Bienes_Raices-MVC",
    demo: "https://github.com/Lean-98/Bienes_Raices-MVC",
  },
  {
    id: 2,
    image: [devwebCamp01, devwebCamp02, devwebCamp03],
    title: "DevWebCamp: Conferences Web Site",
    description: "Conference Site with PayPal Payments, Administration and user management.",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/DevWebCamp-MVC",
    demo: "https://github.com/Lean-98/DevWebCamp-MVC",
  },
  {
    id: 3,
    image: [appSalon01, appSalon02],
    title: "Web Site for Barber Shop and Beauty Salon",
    description: "Complete project of Appointment Management for Beauty Salon",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/App-Salon-mvc",
    demo: "https://github.com/Lean-98/App-Salon-mvc",
  },
  {
    id: 4,
    image: [uptask01, uptask02],
    title: "UpTask: project and task manager",
    description: "",
    techstack: ["#POO" ,"#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/UpTask_MVC",
    demo: "https://github.com/Lean-98/UpTask_MVC",
  },
  {
    id: 5,
    image: [journalApp01, journalApp02],
    title: "JournalApp Web Site",
    description: "",
    techstack: ["#Material MUI" ,"#JavaScript", "#React", "#Redux", "#Redux Toolkit", "#React Router 6", "#Firebase", "#Cloudinary", "#Jest", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/JournalApp",
    demo: "https://journal-app-2k23.netlify.app",
  },
  {
    id: 6,
    image: [starWars01, starWars02],
    title: "Star Wars web site",
    description: "",
    techstack: ["#Bootstrap 5" ,"#JavaScript ", "#React", "#SPA", "#React-Router 6.4", "#Jest", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/StarWars-App",
    demo: "https://starwars-spa-app.netlify.app",
  },
  {
    id: 7,
    image: [festivalMusica01, festivalMusica02, festivalMusica03],
    title: "Music Festival Web Site",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#Gulp", "#JavaScript"],
    github: "https://github.com/Lean-98/festival-musica",
    demo: "https://festivalmusica-by-lean98.netlify.app/",
  },
  {
    id: 8,
    image: [todo01, todo02],
    title: "TodoApp task manager",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#JavaScript", "#Vanilla", "#Vite"],
    github: "https://github.com/Lean-98/TodoApp-V2.0",
    demo: "https://todo-app-by-lean98.netlify.app",
  },
  {
    id: 9,
    image: [devfolioArg01, devfolioArg02],
    title: "Final project for the Front-end course offered by Argentina Program 4.0",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#JavaScript", "#Webpack", "#NPM"],
    github: "https://github.com/Lean-98/PortfolioCv-ARG-4.0",
    demo: "https://lean-98.github.io/PortfolioCv-ARG-4.0",
  },
  {
    id: 10,
    image: [blackJack01, blackJack02],
    title: "BlackJackv2",
    description: "",
    techstack: ["#HTML5" ,"#Bootstrap 5", "#JavaScript", "#Vanilla", "#Vite"],
    github: "https://github.com/Lean-98/BlackJackv2",
    demo: "https://lean-98.github.io/BlackJackv2",
  },
  {
    id: 11,
    image: [hanging01, hanging02],
    title: "Hanging game",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#React", "#Typescript", "#Vite"],
    github: "https://github.com/Lean-98/Hanging_app",
    demo: "https://lean98-hanging.netlify.app",
  },
  {
    id: 12,
    image: [gifExpertApp01, gifExpertApp02],
    title: "GifExpertApp",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#React", "#JavaScript", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/GifExpertApp",
    demo: "https://gif-expertapp-v1.netlify.app",
  },
  {
    id: 13,
    image: [blogCoffe01, blogCoffe02],
    title: "CoffeeBlog",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/blog-coffee",
    demo: "https://blog-coffee-by-lean98.netlify.app",
  },
  {
    id: 14,
    image: [store01, store02],
    title: "Frontend Store",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/front-end-store",
    demo: "https://proyectosweb002.netlify.app",
  },
  {
    id: 15,
    image: [freelancer01, freelancer02],
    title: "FreeLancer Web Site Layout Page",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/FreeLancer2k23",
    demo: "https://freelancer-project-001.netlify.app",
  },
  {
    id: 16,
    image: [maquetaBienesRaices01, maquetaBienesRaices02],
    title: "Real Estate Project Web Site Layout",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#JavaScript"],
    github: "https://github.com/Lean-98/bienes_raices_html-css3",
    demo: "https://bienesraices-by-real10.netlify.app",
  },
];

export const projectsPt = [
  {
    id: 1,
    image: [bienesRaices01, bienesRaices02],
    title: "Site web de imóvei",
    description: "",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/Bienes_Raices-MVC",
    demo: "https://github.com/Lean-98/Bienes_Raices-MVC",
  },
  {
    id: 2,
    image: [devwebCamp01, devwebCamp02, devwebCamp03],
    title: "DevWebCamp: Site web da conferências",
    description: "Site de conferência com pagamentos via PayPal, administração e gerenciamento de usuários.",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/DevWebCamp-MVC",
    demo: "https://github.com/Lean-98/DevWebCamp-MVC",
  },
  {
    id: 3,
    image: [appSalon01, appSalon02],
    title: "Site de barbearia e salão de beleza",
    description: "Projeto completo de gerenciamento de agendamento para salão de beleza.",
    techstack: ["#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/App-Salon-mvc",
    demo: "https://github.com/Lean-98/App-Salon-mvc",
  },
  {
    id: 4,
    image: [uptask01, uptask02],
    title: "UpTask: Site do gerenciador de projetos e tarefas",
    description: "",
    techstack: ["#POO" ,"#PHP8", "#MVC", "#MySQL", "#JavaScript", "#CSS", "#SASS", "#Gulp"],
    github: "https://github.com/Lean-98/UpTask_MVC",
    demo: "https://github.com/Lean-98/UpTask_MVC",
  },
  {
    id: 5,
    image: [journalApp01, journalApp02],
    title: "Site da Web JournalApp",
    description: "",
    techstack: ["#Material MUI" ,"#JavaScript", "#React", "#Redux", "#Redux Toolkit", "#React Router 6", "#Firebase", "#Cloudinary", "#Jest", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/JournalApp",
    demo: "https://journal-app-2k23.netlify.app",
  },
  {
    id: 6,
    image: [starWars01, starWars02],
    title: "Site da Web Star Wars",
    description: "",
    techstack: ["#Bootstrap 5" ,"#JavaScript ", "#React", "#SPA", "#React-Router 6.4", "#Jest", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/StarWars-App",
    demo: "https://starwars-spa-app.netlify.app",
  },
  {
    id: 7,
    image: [festivalMusica01, festivalMusica02, festivalMusica03],
    title: "Site da Web Festival de Música",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#Gulp", "#JavaScript"],
    github: "https://github.com/Lean-98/festival-musica",
    demo: "https://festivalmusica-by-lean98.netlify.app/",
  },
  {
    id: 8,
    image: [todo01, todo02],
    title: "TodoApp: gerenciador de tarefas",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#JavaScript", "#Vanilla", "#Vite"],
    github: "https://github.com/Lean-98/TodoApp-V2.0",
    demo: "https://todo-app-by-lean98.netlify.app",
  },
  {
    id: 9,
    image: [devfolioArg01, devfolioArg02],
    title: "Projeto final do curso Front-end oferecido por Argentina Programa 4.0",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#JavaScript", "#Webpack", "#NPM"],
    github: "https://github.com/Lean-98/PortfolioCv-ARG-4.0",
    demo: "https://lean-98.github.io/PortfolioCv-ARG-4.0",
  },
  {
    id: 10,
    image: [blackJack01, blackJack02],
    title: "BlackJackv2",
    description: "",
    techstack: ["#HTML5" ,"#Bootstrap 5", "#JavaScript", "#Vanilla", "#Vite"],
    github: "https://github.com/Lean-98/BlackJackv2",
    demo: "https://lean-98.github.io/BlackJackv2",
  },
  {
    id: 11,
    image: [hanging01, hanging02],
    title: "Hanging game",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#React", "#Typescript", "#Vite"],
    github: "https://github.com/Lean-98/Hanging_app",
    demo: "https://lean98-hanging.netlify.app",
  },
  {
    id: 12,
    image: [gifExpertApp01, gifExpertApp02],
    title: "GifExpertApp",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#React", "#JavaScript", "#Yarn", "#Vite"],
    github: "https://github.com/Lean-98/GifExpertApp",
    demo: "https://gif-expertapp-v1.netlify.app",
  },
  {
    id: 13,
    image: [blogCoffe01, blogCoffe02],
    title: "BlogDoCafé",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/blog-coffee",
    demo: "https://blog-coffee-by-lean98.netlify.app",
  },
  {
    id: 14,
    image: [store01, store02],
    title: "Frontend Store",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/front-end-store",
    demo: "https://proyectosweb002.netlify.app",
  },
  {
    id: 15,
    image: [freelancer01, freelancer02],
    title: "Layout Site do FreeLancer",
    description: "",
    techstack: ["#HTML5" ,"#CSS"],
    github: "https://github.com/Lean-98/FreeLancer2k23",
    demo: "https://freelancer-project-001.netlify.app",
  },
  {
    id: 16,
    image: [maquetaBienesRaices01, maquetaBienesRaices02],
    title: "Layout de site de projeto imobiliário",
    description: "",
    techstack: ["#HTML5" ,"#CSS", "#SASS", "#JavaScript"],
    github: "https://github.com/Lean-98/bienes_raices_html-css3",
    demo: "https://bienesraices-by-real10.netlify.app",
  },
];
